-- Requête SQL pour lister les OPE_REDO pour les tests de comptes rendus de préparation
-- Fichier : queries/liste_ope_redo.sql

-- 1. REQUÊTE PRINCIPALE : Liste des OPE_REDO avec informations essentielles
SELECT 
    OPE_KEYU,                                    -- Clé unique (int)
    ISNULL(OPE_REDO, '') as OPE_REDO,           -- Numéro de référence (varchar 50)
    ISNULL(OPE_ALPHA17, '') as OPE_ALPHA17,     -- Information complémentaire (varchar 255)
    ISNULL(OPE_CTRA, '') as OPE_CTRA,           -- Code transporteur (varchar 35)
    ISNULL(OPE_ALPHA40, '') as OPE_ALPHA40,     -- Champ alpha 40 (varchar 50)
    ISNULL(OPE_ALPHA41, '') as OPE_ALPHA41,     -- Champ alpha 41 (varchar 50)
    OPE_MODA,                                    -- Date de modification (date)
    ISNULL(OPE_TOP22, 0) as OPE_TOP22,          -- Champ numérique 22 (numeric)
    ISNULL(OPE_STAT, '') as OPE_STAT            -- Statut (varchar 10)
FROM OPE_DAT
WHERE OPE_KEYU IS NOT NULL
  AND OPE_REDO IS NOT NULL
  AND OPE_REDO != ''
ORDER BY OPE_KEYU DESC;

-- 2. REQUÊTE POUR TESTS SPÉCIFIQUES : Récents OPE_REDO seulement
SELECT TOP 20
    OPE_KEYU,
    OPE_REDO,
    OPE_STAT,
    OPE_MODA,
    OPE_CTRA
FROM OPE_DAT
WHERE OPE_REDO IS NOT NULL
  AND OPE_REDO != ''
  AND OPE_KEYU IS NOT NULL
ORDER BY OPE_KEYU DESC;

-- 3. REQUÊTE AVEC STATISTIQUES : Compter les lignes associées
SELECT 
    OPE.OPE_KEYU,
    OPE.OPE_REDO,
    OPE.OPE_STAT,
    OPE.OPE_MODA,
    COUNT(MIL.ART_CODE) as NB_LIGNES_ARTICLES
FROM OPE_DAT OPE
LEFT JOIN MIL_DAT MIL ON OPE.OPE_NoOE = MIL.OPE_NoOE
WHERE OPE.OPE_REDO IS NOT NULL
  AND OPE.OPE_REDO != ''
  AND OPE.OPE_KEYU IS NOT NULL
GROUP BY OPE.OPE_KEYU, OPE.OPE_REDO, OPE.OPE_STAT, OPE.OPE_MODA
ORDER BY OPE.OPE_KEYU DESC;

-- 4. REQUÊTE POUR VALIDATION : Vérifier les OPE_REDO uniques
SELECT 
    OPE_REDO,
    COUNT(*) as NOMBRE_OCCURRENCES
FROM OPE_DAT
WHERE OPE_REDO IS NOT NULL
  AND OPE_REDO != ''
GROUP BY OPE_REDO
HAVING COUNT(*) > 1
ORDER BY NOMBRE_OCCURRENCES DESC;

-- 5. RECHERCHE OPE_REDO SPÉCIFIQUE : Recherche par partie du numéro
-- Remplacer 'PARTIE_NUMERO' par une partie du OPE_REDO recherché
SELECT 
    OPE_KEYU,
    OPE_REDO,
    OPE_STAT,
    OPE_MODA,
    OPE_CTRA,
    OPE_ALPHA17
FROM OPE_DAT
WHERE OPE_REDO LIKE '%PARTIE_NUMERO%'
  AND OPE_REDO IS NOT NULL
ORDER BY OPE_KEYU DESC;

-- 6. RECHERCHE OPE_REDO EXACT : Pour un numéro précis
-- Remplacer 'NUMERO_EXACT' par le OPE_REDO exact recherché
SELECT 
    OPE_KEYU,
    OPE_REDO,
    OPE_STAT,
    OPE_MODA,
    OPE_CTRA,
    OPE_ALPHA17,
    OPE_ALPHA40,
    OPE_ALPHA41,
    OPE_TOP22
FROM OPE_DAT
WHERE OPE_REDO = 'NUMERO_EXACT';

-- 7. RECHERCHE AVEC PATTERN : Pour rechercher selon un motif
-- Exemples d'utilisation :
-- OPE_REDO LIKE 'BL%'        --> Commence par "BL"
-- OPE_REDO LIKE '%2024%'     --> Contient "2024"
-- OPE_REDO LIKE 'BL_____'    --> "BL" suivi de 5 caractères exactement
SELECT 
    OPE_KEYU,
    OPE_REDO,
    OPE_STAT,
    OPE_MODA
FROM OPE_DAT
WHERE OPE_REDO LIKE 'VOTRE_PATTERN'
  AND OPE_REDO IS NOT NULL
ORDER BY OPE_REDO;

-- 8. REQUÊTE DIAGNOSTIC COMPLÈTE : Structure des données pour un OPE_REDO spécifique
-- Remplacer 'VOTRE_OPE_REDO' par une valeur réelle pour tester
SELECT 
    'En-tête BL' as TYPE_DONNEE,
    OPE_KEYU as REFERENCE,
    OPE_REDO as NUMERO,
    OPE_STAT as STATUT,
    NULL as ART_CODE,
    NULL as QUANTITE
FROM OPE_DAT
WHERE OPE_REDO = 'VOTRE_OPE_REDO'

UNION ALL

SELECT 
    'Ligne article' as TYPE_DONNEE,
    CAST(OPE.OPE_KEYU AS VARCHAR(10)) as REFERENCE,
    OPE.OPE_REDO as NUMERO,
    NULL as STATUT,
    MIL.ART_CODE,
    CAST(MIL.MIL_QTTP AS VARCHAR(20)) as QUANTITE
FROM OPE_DAT OPE
INNER JOIN MIL_DAT MIL ON OPE.OPE_NoOE = MIL.OPE_NoOE
WHERE OPE.OPE_REDO = 'VOTRE_OPE_REDO'
ORDER BY TYPE_DONNEE, REFERENCE;

-- 10. DIAGNOSTIC SPÉCIFIQUE : Rechercher votre cas problématique
-- Recherche du BL contenant "2706114963"
SELECT 
    OPE_KEYU,
    OPE_REDO,                    -- TransRefId dans Dynamics
    OPE_ALPHA17,                 -- PickingRouteID dans Dynamics ← PROBLÈME POTENTIEL
    OPE_CTRA,                    -- CarrierCode
    OPE_ALPHA40,                 -- Partie 1 CarrierServiceCode
    OPE_ALPHA41,                 -- Partie 2 CarrierServiceCode
    OPE_STAT,
    OPE_MODA
FROM OPE_DAT
WHERE OPE_REDO LIKE '%2706114963%'
   OR OPE_ALPHA17 LIKE '%2706114963%'
   OR OPE_KEYU LIKE '%2706114963%';

-- 11. ANALYSE MAPPING COMPLET : Vérifier toutes les colonnes pour ce BL
SELECT 
    '🔍 MAPPING SPEEDWMS → DYNAMICS' as INFO,
    OPE_KEYU as BL_NUMBER,
    OPE_REDO as TRANS_REF_ID,
    OPE_ALPHA17 as PICKING_ROUTE_ID,      -- ← C'est ici le problème !
    OPE_CTRA as CARRIER_CODE,
    CONCAT(OPE_ALPHA40, OPE_ALPHA41) as CARRIER_SERVICE_CODE,
    OPE_STAT,
    OPE_TOP22,
    OPE_MODA
FROM OPE_DAT
WHERE OPE_REDO = '2706114963';

-- 12. RECHERCHE INVERSÉE : Trouver où est stocké "2706114963.734101-A3"
SELECT 
    'OPE_REDO contient la valeur complète' as LOCALISATION,
    OPE_KEYU,
    OPE_REDO
FROM OPE_DAT
WHERE OPE_REDO LIKE '%2706114963.734101-A3%'

UNION ALL

SELECT 
    'OPE_ALPHA17 contient la valeur complète' as LOCALISATION,
    OPE_KEYU,
    OPE_ALPHA17
FROM OPE_DAT
WHERE OPE_ALPHA17 LIKE '%2706114963.734101-A3%'

UNION ALL

SELECT 
    'Autre colonne contient la valeur complète' as LOCALISATION,
    OPE_KEYU,
    CONCAT('ALPHA40:', OPE_ALPHA40, ' | ALPHA41:', OPE_ALPHA41, ' | CTRA:', OPE_CTRA)
FROM OPE_DAT
WHERE OPE_ALPHA40 LIKE '%2706114963.734101-A3%'
   OR OPE_ALPHA41 LIKE '%2706114963.734101-A3%'
   OR OPE_CTRA LIKE '%2706114963.734101-A3%';

-- 13. VALIDATION DES DONNÉES : Comparer toutes les valeurs possibles
SELECT 
    OPE_KEYU,
    'OPE_REDO: ' + ISNULL(OPE_REDO, 'NULL') as CHAMP_1,
    'OPE_ALPHA17: ' + ISNULL(OPE_ALPHA17, 'NULL') as CHAMP_2,
    'OPE_ALPHA40: ' + ISNULL(OPE_ALPHA40, 'NULL') as CHAMP_3,
    'OPE_ALPHA41: ' + ISNULL(OPE_ALPHA41, 'NULL') as CHAMP_4,
    'OPE_CTRA: ' + ISNULL(OPE_CTRA, 'NULL') as CHAMP_5
FROM OPE_DAT
WHERE OPE_REDO LIKE '%2706114963%'
   OR OPE_ALPHA17 LIKE '%2706114963%'
   OR OPE_ALPHA40 LIKE '%2706114963%'
   OR OPE_ALPHA41 LIKE '%2706114963%'
   OR OPE_CTRA LIKE '%2706114963%';

-- 15. ANALYSE COMPLÈTE OPE_ALPHA17 : Vérifier toutes les valeurs
SELECT 
    'STATISTIQUES OPE_ALPHA17' as TYPE_ANALYSE,
    COUNT(*) as TOTAL_LIGNES,
    SUM(CASE WHEN OPE_ALPHA17 IS NULL THEN 1 ELSE 0 END) as NULL_COUNT,
    SUM(CASE WHEN OPE_ALPHA17 = '' THEN 1 ELSE 0 END) as VIDE_COUNT,
    SUM(CASE WHEN OPE_ALPHA17 IS NOT NULL AND OPE_ALPHA17 != '' THEN 1 ELSE 0 END) as RENSEIGNE_COUNT
FROM OPE_DAT;

-- 16. VISUALISER TOUS LES OPE_ALPHA17 RENSEIGNÉS
SELECT 
    OPE_KEYU,
    OPE_REDO,
    OPE_ALPHA17,
    LEN(OPE_ALPHA17) as LONGUEUR_ALPHA17,
    OPE_STAT,
    OPE_MODA
FROM OPE_DAT
WHERE OPE_ALPHA17 IS NOT NULL 
  AND OPE_ALPHA17 != ''
  AND LTRIM(RTRIM(OPE_ALPHA17)) != ''
ORDER BY OPE_KEYU DESC;

-- 17. ÉCHANTILLON COMPLET : Voir les différents cas de figure
SELECT TOP 20
    OPE_KEYU,
    CASE 
        WHEN OPE_ALPHA17 IS NULL THEN '🔴 NULL'
        WHEN OPE_ALPHA17 = '' THEN '🟡 VIDE'
        WHEN LTRIM(RTRIM(OPE_ALPHA17)) = '' THEN '🟡 ESPACES'
        ELSE '🟢 RENSEIGNÉ'
    END as STATUT_ALPHA17,
    '[' + ISNULL(OPE_ALPHA17, 'NULL') + ']' as ALPHA17_AVEC_CROCHETS,
    OPE_REDO,
    OPE_STAT
FROM OPE_DAT
ORDER BY OPE_KEYU DESC;

-- 18. RECHERCHE PATTERN SPÉCIFIQUE : Formats d'OPE_ALPHA17
SELECT DISTINCT
    CASE 
        WHEN OPE_ALPHA17 IS NULL THEN 'NULL'
        WHEN OPE_ALPHA17 = '' THEN 'VIDE'
        WHEN OPE_ALPHA17 LIKE '%-%' THEN 'CONTIENT_TIRET'
        WHEN OPE_ALPHA17 LIKE '%.%' THEN 'CONTIENT_POINT'
        WHEN ISNUMERIC(OPE_ALPHA17) = 1 THEN 'NUMERIQUE_SEUL'
        WHEN LEN(OPE_ALPHA17) > 20 THEN 'TROP_LONG'
        ELSE 'AUTRE_FORMAT'
    END as TYPE_FORMAT,
    COUNT(*) as NOMBRE_OCCURRENCES,
    MIN(OPE_ALPHA17) as EXEMPLE_VALEUR
FROM OPE_DAT
GROUP BY 
    CASE 
        WHEN OPE_ALPHA17 IS NULL THEN 'NULL'
        WHEN OPE_ALPHA17 = '' THEN 'VIDE'
        WHEN OPE_ALPHA17 LIKE '%-%' THEN 'CONTIENT_TIRET'
        WHEN OPE_ALPHA17 LIKE '%.%' THEN 'CONTIENT_POINT'
        WHEN ISNUMERIC(OPE_ALPHA17) = 1 THEN 'NUMERIQUE_SEUL'
        WHEN LEN(OPE_ALPHA17) > 20 THEN 'TROP_LONG'
        ELSE 'AUTRE_FORMAT'
    END
ORDER BY NOMBRE_OCCURRENCES DESC;

-- 19. DIAGNOSTIC POUR VOTRE BL SPÉCIFIQUE
SELECT 
    '🔍 DIAGNOSTIC BL 2706114963' as INFO,
    OPE_KEYU,
    OPE_REDO,
    CASE 
        WHEN OPE_ALPHA17 IS NULL THEN '❌ OPE_ALPHA17 = NULL'
        WHEN OPE_ALPHA17 = '' THEN '❌ OPE_ALPHA17 = VIDE'
        ELSE '✅ OPE_ALPHA17 = [' + OPE_ALPHA17 + ']'
    END as DIAGNOSTIC_ALPHA17,
    OPE_CTRA,
    OPE_STAT
FROM OPE_DAT
WHERE OPE_REDO LIKE '%2706114963%';

-- 20. SOLUTION ALTERNATIVE : Utiliser OPE_REDO comme pickingRouteID
-- Cette requête montre ce qui devrait être envoyé à Dynamics
SELECT 
    '💡 SOLUTION PROPOSÉE' as TYPE,
    OPE_KEYU as BLNumber,
    OPE_REDO as TransRefId,
    OPE_REDO as PickingRouteID_PROPOSE,    -- ✅ Utiliser OPE_REDO au lieu d'OPE_ALPHA17
    CASE 
        WHEN OPE_ALPHA17 IS NULL OR OPE_ALPHA17 = '' THEN '✅ Utiliser OPE_REDO'
        ELSE '⚠️ Vérifier si OPE_ALPHA17 existe dans Dynamics'
    END as RECOMMANDATION,
    OPE_CTRA as CarrierCode
FROM OPE_DAT
WHERE OPE_REDO IS NOT NULL 
  AND OPE_REDO != ''
ORDER BY OPE_KEYU DESC;

-- 22. RECHERCHE SPÉCIFIQUE : Vérifier si "2706114963.734101-A3" existe dans OPE_ALPHA17
SELECT 
    '🔍 RECHERCHE EXACTE DANS ALPHA17' as TYPE_RECHERCHE,
    OPE_KEYU,
    OPE_REDO,
    OPE_ALPHA17,
    CASE 
        WHEN OPE_ALPHA17 = '2706114963.734101-A3' THEN '✅ CORRESPONDANCE EXACTE'
        WHEN OPE_ALPHA17 LIKE '%2706114963.734101-A3%' THEN '✅ CORRESPONDANCE PARTIELLE'
        ELSE '❌ PAS DE CORRESPONDANCE'
    END as RESULTAT
FROM OPE_DAT
WHERE OPE_ALPHA17 = '2706114963.734101-A3'
   OR OPE_ALPHA17 LIKE '%2706114963.734101-A3%';

-- 23. RECHERCHE ÉLARGIE : Toutes les colonnes pour cette valeur
SELECT 
    '🔍 RECHERCHE DANS TOUTES LES COLONNES' as TYPE_RECHERCHE,
    OPE_KEYU,
    CASE 
        WHEN OPE_REDO LIKE '%2706114963.734101-A3%' THEN 'OPE_REDO'
        WHEN OPE_ALPHA17 LIKE '%2706114963.734101-A3%' THEN 'OPE_ALPHA17'
        WHEN OPE_ALPHA40 LIKE '%2706114963.734101-A3%' THEN 'OPE_ALPHA40'
        WHEN OPE_ALPHA41 LIKE '%2706114963.734101-A3%' THEN 'OPE_ALPHA41'
        WHEN OPE_CTRA LIKE '%2706114963.734101-A3%' THEN 'OPE_CTRA'
        ELSE 'INTROUVABLE'
    END as COLONNE_TROUVEE,
    OPE_REDO,
    OPE_ALPHA17,
    OPE_ALPHA40,
    OPE_ALPHA41,
    OPE_CTRA
FROM OPE_DAT
WHERE OPE_REDO LIKE '%2706114963.734101-A3%'
   OR OPE_ALPHA17 LIKE '%2706114963.734101-A3%'
   OR OPE_ALPHA40 LIKE '%2706114963.734101-A3%'
   OR OPE_ALPHA41 LIKE '%2706114963.734101-A3%'
   OR OPE_CTRA LIKE '%2706114963.734101-A3%';

-- 24. VALIDATION GÉNÉRIQUE : Template pour vérifier n'importe quelle valeur d'erreur
-- Remplacer 'VALEUR_ERREUR_ICI' par la valeur du message d'erreur
SELECT 
    '🔍 TEMPLATE RECHERCHE ERREUR' as TYPE,
    OPE_KEYU,
    'TROUVÉ DANS: ' + 
    CASE 
        WHEN OPE_ALPHA17 = 'VALEUR_ERREUR_ICI' THEN 'OPE_ALPHA17 (EXACT)'
        WHEN OPE_ALPHA17 LIKE '%VALEUR_ERREUR_ICI%' THEN 'OPE_ALPHA17 (PARTIEL)'
        WHEN OPE_REDO = 'VALEUR_ERREUR_ICI' THEN 'OPE_REDO (EXACT)'
        WHEN OPE_REDO LIKE '%VALEUR_ERREUR_ICI%' THEN 'OPE_REDO (PARTIEL)'
        ELSE 'INTROUVABLE'
    END as LOCALISATION,
    OPE_REDO,
    OPE_ALPHA17
FROM OPE_DAT
WHERE OPE_ALPHA17 = 'VALEUR_ERREUR_ICI'
   OR OPE_ALPHA17 LIKE '%VALEUR_ERREUR_ICI%'
   OR OPE_REDO = 'VALEUR_ERREUR_ICI'
   OR OPE_REDO LIKE '%VALEUR_ERREUR_ICI%';

-- 25. RECHERCHE SPÉCIFIQUE POUR VOTRE CAS : "2706114963.734101-A3"
-- Cette requête cherche cette valeur exacte dans votre base
SELECT 
    CASE 
        WHEN COUNT(*) = 0 THEN '❌ VALEUR "2706114963.734101-A3" INTROUVABLE DANS LA BASE'
        ELSE '✅ VALEUR TROUVÉE ' + CAST(COUNT(*) AS VARCHAR(10)) + ' FOIS'
    END as RESULTAT_RECHERCHE
FROM OPE_DAT
WHERE OPE_ALPHA17 = '2706114963.734101-A3'
   OR OPE_REDO = '2706114963.734101-A3'
   OR OPE_ALPHA40 = '2706114963.734101-A3'
   OR OPE_ALPHA41 = '2706114963.734101-A3'
   OR OPE_CTRA = '2706114963.734101-A3';

-- 26. ANALYSE DU PROBLÈME : Comprendre d'où vient cette valeur
SELECT 
    '🔧 ANALYSE PROBLÈME' as TYPE,
    OPE_KEYU,
    OPE_REDO as REDO_DANS_BASE,
    OPE_ALPHA17 as ALPHA17_DANS_BASE,
    CASE 
        WHEN OPE_ALPHA17 IS NULL OR OPE_ALPHA17 = '' THEN 
            '💡 ALPHA17 VIDE → Code utilise probablement une valeur par défaut ou calculée'
        ELSE 
            '💡 ALPHA17 = [' + OPE_ALPHA17 + ']'
    END as DIAGNOSTIC,
    '2706114963.734101-A3' as VALEUR_DANS_ERREUR
FROM OPE_DAT
WHERE OPE_REDO LIKE '%2706114963%';